[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "pyaudio>=0.2.14",
    "pyttsx3>=2.98",
    "vosk>=0.3.45",
]
